### ISSUE TITLE
Wrong requirements support for Mac x86

### ISSUE THREAD

**Issue by Norfolks** [near/near-workspaces-rs#385]
I am working on a pretty oldish MacBook Pro 2015.
And I have runtime issues with starting a sandbox for all new workspaces releases up to version 11.1, however, it is [mentioned](https://github.com/near/near-workspaces-rs?tab=readme-ov-file#requirements) that this setup is supported.
Log example:
```
error: failed to run custom build command for `near-workspaces v0.14.1`

Caused by:
  process didn't exit successfully: `/Users/Nick/Projects/mem-starter/target/debug/build/near-workspaces-376981cba5e4ceef/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NEAR_SANDBOX_BIN_PATH

  --- stderr
  thread 'main' panicked at /Users/Nick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/near-workspaces-0.14.1/build.rs:7:39:
  Could not install sandbox: Unsupported platform: only linux-x86 and darwin-arm are supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by frol** [comment]
If I remember correctly, there are no near-sandbox pre-built binaries for MacOS x86, so we should update near-sandbox and the README

**Comment by think-in-universe** [comment]
I have the same issue on MacOS x86. 

Does this mean we can no longer run sandbox testing locally in Mac Intel CPU machines?

What's the reason to not support near-sandbox pre-built binaries for MacOS x86?

```
Caused by:
  process didn't exit successfully: `....../target/debug/build/near-workspaces-fc9bc29b288ef571/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=NEAR_SANDBOX_BIN_PATH

  --- stderr

  thread 'main' panicked at ~/.cargo/registry/src/mirrors.aliyun.com-0671735e7cc7f5e7/near-workspaces-0.20.1/build.rs:7:39:
  Could not install sandbox: Unsupported platform: only linux-x86 and darwin-arm are supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [lint] Error 101
```
